name: AKS Kubectl Get All

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-k8s-resources:
    runs-on: self-hosted

    steps:

    - name: Run kubectl get all
      run: |
        az account set --subscription 6a7163f8-b2ab-4734-b784-c8ac54dea875
        az aks get-credentials --resource-group rg-svcp-lab-sr --name aks-test --overwrite-existing
        az aks command invoke --resource-group rg-svcp-lab-sr --name aks-test --command 'kubectl get nodes'
